# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-31 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
