# Generated by Django 2.0.4 on 2018-06-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180529_0517'),
        ('users', '0006_auto_20180604_2225'),
    ]

    operations = [
    ]
