# Generated by Django 2.0.4 on 2018-06-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20180611_2117'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='user',
        #     name='group',
        #     field=models.IntegerField(default=3),
        # ),
    ]
