# Generated by Django 2.0.4 on 2018-06-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_group'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='user',
    #         name='group',
    #     ),
    # ]
