# Generated by Django 2.0.4 on 2018-06-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_group'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='user',
        #     name='group',
        #     field=models.IntegerField(default=3),
        # ),
    ]
