# Generated by Django 2.0.4 on 2018-06-25 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_group'),
        ('users', '0009_user_group'),
    ]

    operations = [
    ]
