# Generated by Django 2.0.4 on 2018-06-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20180625_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='store_type',
        ),
        migrations.AddField(
            model_name='store',
            name='available_items',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
