# Generated by Django 2.0.4 on 2018-06-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20180625_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='available_items',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='keywords',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
