# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-29 18:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('logo', models.FileField(upload_to='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, default=0.0)),
                ('size', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('specifications', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
#
# # Generated by Django 2.0.4 on 2018-06-03 18:33
# from __future__ import unicode_literals
# import datetime
# from django.conf import settings
# from django.db import migrations, models
# import django.db.models.deletion
#
#
# class Migration(migrations.Migration):
#
#     initial = True
#
#     dependencies = [
#         migrations.swappable_dependency(settings.AUTH_USER_MODEL),
#     ]
#
#     operations = [
#         migrations.CreateModel(
#             name='Brand',
#             fields=[
#                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('title', models.CharField(max_length=255)),
#                 ('logo', models.FileField(upload_to='')),
#                 ('created_on', models.DateTimeField(auto_now_add=True)),
#             ],
#         ),
#         migrations.CreateModel(
#             name='Category',
#             fields=[
#                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('title', models.CharField(max_length=255)),
#                 ('slug', models.SlugField(max_length=255, unique=True)),
#                 ('created_on', models.DateTimeField(auto_now_add=True)),
#             ],
#             options={
#                 'ordering': ['created_on'],
#             },
#         ),
#         migrations.CreateModel(
#             name='Product',
#             fields=[
#                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('title', models.CharField(blank=True, max_length=255)),
#                 ('created_on', models.DateTimeField(auto_now_add=True)),
#                 ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Brand')),
#                 ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
#             ],
#         ),
#         migrations.CreateModel(
#             name='ProductDetails',
#             fields=[
#                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('price', models.FloatField(blank=True, default=0.0)),
#                 ('size', models.CharField(max_length=50)),
#                 ('color', models.CharField(max_length=50)),
#                 ('description', models.TextField(blank=True, max_length=1000)),
#                 ('specifications', models.TextField(blank=True, max_length=1000)),
#                 ('status', models.CharField(blank=True, max_length=255)),
#                 ('created_on', models.DateTimeField(auto_now_add=True)),
#                 ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
#             ],
#         ),
#         migrations.CreateModel(
#             name='ProductUploads',
#             fields=[
#                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('filename', models.CharField(blank=True, max_length=255)),
#                 ('file', models.ImageField(default='product/image.jpg', upload_to='product')),
#                 ('filetype', models.IntegerField(blank=True)),
#                 ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
#                 ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
#             ],
#             options={
#                 'verbose_name': 'photo',
#                 'verbose_name_plural': 'photos',
#             },
#         ),
#         migrations.CreateModel(
#             name='Subcategory',
#             fields=[
#                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('title', models.CharField(max_length=255)),
#                 ('slug', models.SlugField(max_length=255, unique=True)),
#                 ('created_on', models.DateTimeField(auto_now_add=True)),
#                 ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
#             ],
#         ),
#         migrations.AddField(
#             model_name='product',
#             name='subcategory',
#             field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Subcategory'),
#         ),
#         migrations.AddField(
#             model_name='product',
#             name='user',
#             field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
#         ),
#     ]
