# Generated by Django 2.0.4 on 2018-06-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productuploads',
            options={},
        ),
        migrations.AlterField(
            model_name='productuploads',
            name='filename',
            field=models.CharField(max_length=255, null=True),
        ),
        # migrations.AlterField(
        #     model_name='productuploads',
        #     name='filetype',
        #     field=models.IntegerField(null=True),
        # ),
    ]
