# Generated by Django 2.0.4 on 2018-06-10 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180605_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productuploads',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
