# Generated by Django 2.0.4 on 2018-06-10 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180611_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productuploads',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
