# Generated by Django 2.0.4 on 2018-06-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20180611_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productuploads',
            name='type',
        ),
        migrations.AddField(
            model_name='productuploads',
            name='file',
            field=models.ImageField(default='product/image.jpg', upload_to='product'),
        ),
        migrations.AddField(
            model_name='productuploads',
            name='filetype',
            field=models.IntegerField(null=True),
        ),
    ]
