# Generated by Django 2.0.4 on 2018-10-24 09:54

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20181024_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productuploads',
            name='file',
            field=models.ImageField(upload_to=product.models.custom_filename),
        ),
    ]
