# Generated by Django 2.0.4 on 2018-10-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20181024_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productuploads',
            name='file',
            field=models.ImageField(upload_to='product/'),
        ),
    ]
