# Generated by Django 2.0.4 on 2018-06-03 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productuploads',
            old_name='type',
            new_name='filetype',
        ),
    ]
