# Generated by Django 2.0.4 on 2018-06-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180603_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='productuploads',
            name='file',
            field=models.ImageField(default='media/image.jpg', upload_to='media'),
        ),
    ]
