# Generated by Django 2.0.4 on 2018-06-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productuploads_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productuploads',
            old_name='uploaded_at',
            new_name='created_on',
        ),
        migrations.AlterField(
            model_name='productuploads',
            name='file',
            field=models.ImageField(default='product/image.jpg', upload_to='product'),
        ),
    ]
