# Generated by Django 2.0.4 on 2018-06-03 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20180603_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productuploads',
            old_name='created_on',
            new_name='uploaded_at',
        ),
    ]
