# Generated by Django 2.0.4 on 2018-06-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20180603_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productuploads',
            old_name='uploaded_at',
            new_name='created_on',
        ),
    ]
