# Generated by Django 2.0.4 on 2018-06-03 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20180603_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productuploads',
            name='created_on',
        ),
    ]
