# Generated by Django 2.0.4 on 2018-06-03 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20180604_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='productuploads',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
