# Generated by Django 2.0.4 on 2018-06-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productuploads_uploaded_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productuploads',
            old_name='uploaded_at',
            new_name='created_on',
        ),
    ]
