# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-03 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso3',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='country',
            name='numcode',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='country',
            name='phonecode',
            field=models.CharField(max_length=5),
        ),
    ]
