export const FETCH_USER_INFO_BEGINS = "FETCH_USER_INFO_BEGINS";
export const FETCH_USER_INFO_SUCCESS = "FETCH_USER_INFO_SUCCESS";
export const FETCH_USER_INFO_FAILURE = "FETCH_USER_INFO_FAILURE";
export const LOGOUT_USER = "LOGOUT_USER";

export const FETCH_STORE_BEGINS = "FETCH_STORE_BEGINS";
export const FETCH_STORE_SUCCESS = "FETCH_STORE_SUCCESS";
export const FETCH_STORE_FAILURE = "FETCH_STORE_FAILURE";

export const FETCH_ALL_PRODUCT_BEGINS = "FETCH_ALL_PRODUCT_BEGINS";
export const FETCH_ALL_PRODUCT_SUCCESS = "FETCH_ALL_PRODUCT_SUCCESS";
export const FETCH_ALL_PRODUCT_FAILURE = "FETCH_ALL_PRODUCT_FAILURE";

export const FETCH_PRODUCT_BEGINS = "FETCH_PRODUCT_BEGINS";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAILURE = "FETCH_PRODUCT_FAILURE";

export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";